[package]
name = "syncbox"
version = "0.1.1"
edition = "2024"
authors = ["LiGang<ligang13874843373@gmail.com>"]
description = "一个类似 rsync 的文件同步工具"
homepage = "https://github.com/ligang-code2020/syncbox"
license = "MIT"
readme = "README.md"
keywords = ["sync", "file-sync", "rsync", "syncbox"]
categories = ["command-line-utilities"]  # 分类（参考 crates.io 分类列表）




[[bin]]
name = "syncbox"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.46", features = ["derive"] }
anyhow = "1.0.99"
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1.47.1", features = ["full"] }
toml = "0.9.5"
notify = "8.1.0"
tokio-util = { version = "0.7.16" }
time = "0.3.41"
tracing = "0.1.41"
tracing-subscriber = { version = " 0.3.19", features = ["env-filter", "fmt"] }
thiserror = "2.0.16"
walkdir = "2.5.0"
indicatif = "0.18.0"
blake3 = "1.8.2"
num-format = "0.4.4"
regex = "1.11.2"
chrono = "0.4.42"



# dev-dependencies
[dev-dependencies]
tempfile = "3.8"
tokio-test = "0.4"
