# syncbox.toml
[[sync]]
name = "task"
source = "/Users/lg/Desktop/syncbox/source"
target = "/Users/lg/Desktop/syncbox/target"
#exclude = [".secret"]
delete_extra = false
#delete_extra_exclude = [".DS_Store"]





