# syncbox.toml
[[sync]]
name = "task"
source = "/Users/lg/Desktop/syncbox/source"
target = "/Users/lg/Desktop/syncbox/target"
exclude = ["file_1.txt","file_2.txt"]
delete_extra = true
delete_extra_exclude = [".DS_Store"]





