# syncbox.toml
[[sync]]
name = "task"
source = "/Users/lg/Desktop/syncbox/source"
target = "/Users/lg/Desktop/syncbox/target"
exclude = [".secret"]
delete_extra = true
delete_extra_exclude = [".DS_Store"]


# cargo run -- sync /Users/lg/Desktop/syncbox/source user@host:/remote/path --dry-run


